# Generated by Django 3.0.5 on 2020-04-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='context',
            field=models.TextField(null=True),
        ),
    ]
